### ISSUE TITLE
gmsh.initialize() error

### ISSUE THREAD

**Issue by AndriusT** [jackbkennedy/onelab#1]
Hi, 

I have successfully installed Onelab on macOS Catalina (v. 10.15) using pip and was going through the given sample code. Upon running gmsh.initialize() I get the following error: 

AttributeError: dlsym(RTLD_DEFAULT, gmshInitialize): symbol not found

Thanks for your help!

Andrius

**Comment by jackbkennedy** [comment]
Hey Andrius, will take a look at this tomorrow and push an update if I find the issue. I haven't been keeping up with the recent versions of Gmsh so if you are using the most recent version that might be the issue. Thanks

**Comment by jackbkennedy** [comment]
Andrius I took a look at this and I could not reproduce the error. I bumped my version of Gmsh to the most recent release and the package still seems to run correctly. Could you give me a few more details like what version of Gmsh you are running? Since I released this package Gmsh now lets you download the application and api directly from pip (https://pypi.org/project/gmsh-dev/) so you could try this also.
